# Configurable start

theme: jekyll-theme-cayman
title: "SAP Business Technology Platform"
description: "Some tips and materials for developing and extending SAP applications in a Cloud."
url: "https://mamartinezfernandez.github.io"
signoff: "Manuel"
github_username:  mamartinezfernandez
